- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Restart containerd (with built-in CRI support)
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Verify CRI plugin is available
  command: crictl info
  register: cri_info
  failed_when: "'unimplemented' in cri_info.stderr.lower()"

- name: Initialize Kubernetes cluster with containerd
  command: >
    kubeadm init
    --apiserver-advertise-address=192.168.56.11
    --pod-network-cidr=10.244.0.0/16
    --ignore-preflight-errors=all
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_output

- name: Set up kubeconfig for the default user
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    executable: /bin/bash
  when: kubeadm_output is succeeded

- name: Install Calico networking plugin
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

