- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure containerd service is restarted and enabled
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Verify CRI plugin is available
  command: crictl info
  register: cri_info
  failed_when: "'unimplemented' in cri_info.stderr.lower()"

- name: Join worker node to Kubernetes cluster
  command: >
    kubeadm join 192.168.56.11:6443
    --token imczv8.bclkzx68wmiyqxfj
    --discovery-token-ca-cert-hash sha256:be3ec6ac778072e42dad4833d7a1c08d11b7c900e8a217bfc1a1439684b20cb8
    --ignore-preflight-errors=all
  args:
    creates: /etc/kubernetes/kubelet.conf

