all:
  children:
    jump:
      hosts:
        bastion:
          ansible_host: 192.168.56.10
    master:
      hosts:
        control:
          ansible_host: 192.168.56.11
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.56.12
        worker2:
          ansible_host: 192.168.56.13

  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: /home/vagrant/.ssh/homelab_key
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -W %h:%p -i /home/vagrant/.ssh/homelab_key vagrant@192.168.56.10"
